version: '3'

services:

  mysql_gbk:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=dz
    ports:
      - "3306:3306"
    volumes:
      - ./runtime/3.4/mysql:/var/lib/mysql

  web_gbk:
    build:
      context: ./build/docker
      dockerfile: ./build/docker/Dockerfile_gbk
    ports:
      - "80:80"
    volumes:
      - ./app.conf:/etc/nginx/http.d/default.conf
      - ./runtime/3.4/config:/var/www/html/config
      - ./src/dist/gbk:/var/www/html/source/plugin/codfrm_markdown
    links:
      - "mysql:database"

